-- Phase 6.1: Audit Evidence Tables
-- Migration: 001_audit_evidence_tables.sql
-- Created: 2026-05-08
-- Purpose: Immutable evidence packages for SOC 2 / HIPAA audit readiness
--
-- Tables:
--   evidence_packages  - Records of packaged audit log bundles (S3 Object Lock)
--   macie_findings     - AWS Macie PII scan findings on log buckets
--
-- All tables enforce Row-Level Security (RLS) for multi-tenant isolation.
-- Set: SET app.current_customer_id = '<uuid>' before querying.

-- ============================================================================
-- Extensions (idempotent)
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- evidence_packages
-- Records every compliance evidence bundle generated by audit_log_packager.py.
-- The actual zip file is stored in S3 with Object Lock (COMPLIANCE mode).
-- ============================================================================

CREATE TABLE IF NOT EXISTS evidence_packages (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_id         UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    package_name        VARCHAR(255) NOT NULL,
    s3_bucket           VARCHAR(255) NOT NULL,
    s3_key              VARCHAR(1024) NOT NULL,
    s3_version_id       VARCHAR(255),                        -- S3 Object Lock version
    sha256_manifest     TEXT NOT NULL,                       -- SHA-256 hex digest of the zip
    framework           VARCHAR(50) NOT NULL                 -- 'SOC2', 'HIPAA', 'FedRAMP', 'ALL'
                        CHECK (framework IN ('SOC2', 'HIPAA', 'FedRAMP', 'ALL')),
    date_range_start    TIMESTAMPTZ NOT NULL,
    date_range_end      TIMESTAMPTZ NOT NULL,
    log_count           INTEGER NOT NULL DEFAULT 0,
    package_size_bytes  BIGINT NOT NULL DEFAULT 0,
    status              VARCHAR(30) NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'processing', 'complete', 'error')),
    error_message       TEXT,
    retention_until     TIMESTAMPTZ NOT NULL,                -- Must match S3 Object Lock expiry
    generated_by        UUID REFERENCES users(id),           -- NULL = system/Lambda
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_evidence_packages_customer_id
    ON evidence_packages (customer_id);

CREATE INDEX IF NOT EXISTS idx_evidence_packages_framework
    ON evidence_packages (customer_id, framework);

CREATE INDEX IF NOT EXISTS idx_evidence_packages_created_at
    ON evidence_packages (customer_id, created_at DESC);

-- ============================================================================
-- macie_findings
-- Records AWS Macie PII classification findings on audit log S3 buckets.
-- Used to alert on accidental PHI/PII exposure in log data.
-- ============================================================================

CREATE TABLE IF NOT EXISTS macie_findings (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_id         UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    macie_finding_id    VARCHAR(255) NOT NULL UNIQUE,        -- Macie native finding ID
    s3_bucket           VARCHAR(255) NOT NULL,
    s3_key              VARCHAR(1024),
    finding_type        VARCHAR(100) NOT NULL,               -- e.g. 'SensitiveData:S3Object/Personal'
    severity            VARCHAR(20) NOT NULL
                        CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    pii_type            VARCHAR(100),                        -- e.g. 'NAME', 'EMAIL', 'SSN', 'PHI'
    occurrence_count    INTEGER NOT NULL DEFAULT 0,
    status              VARCHAR(30) NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'suppressed', 'resolved')),
    suppression_reason  TEXT,
    resolved_at         TIMESTAMPTZ,
    resolved_by         UUID REFERENCES users(id),
    raw_finding         JSONB,                               -- Full Macie finding JSON
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_macie_findings_customer_id
    ON macie_findings (customer_id);

CREATE INDEX IF NOT EXISTS idx_macie_findings_severity
    ON macie_findings (customer_id, severity, status);

CREATE INDEX IF NOT EXISTS idx_macie_findings_created_at
    ON macie_findings (customer_id, created_at DESC);

-- ============================================================================
-- Row-Level Security Policies
-- ============================================================================

ALTER TABLE evidence_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE macie_findings    ENABLE ROW LEVEL SECURITY;

-- evidence_packages: tenant isolation
CREATE POLICY evidence_packages_tenant_isolation
    ON evidence_packages
    USING (
        customer_id = current_setting('app.current_customer_id', true)::UUID
    );

-- macie_findings: tenant isolation
CREATE POLICY macie_findings_tenant_isolation
    ON macie_findings
    USING (
        customer_id = current_setting('app.current_customer_id', true)::UUID
    );

-- ============================================================================
-- Triggers: keep updated_at current
-- ============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_evidence_packages_updated_at
    BEFORE UPDATE ON evidence_packages
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_macie_findings_updated_at
    BEFORE UPDATE ON macie_findings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON TABLE evidence_packages IS
    'Immutable records of SOC2/HIPAA/FedRAMP evidence bundles stored in S3 with Object Lock (Phase 6.1).';

COMMENT ON TABLE macie_findings IS
    'AWS Macie PII classification findings on audit log S3 buckets (Phase 6.1).';

COMMENT ON COLUMN evidence_packages.sha256_manifest IS
    'SHA-256 hex digest of the zip archive. Must be verified on every download.';

COMMENT ON COLUMN evidence_packages.retention_until IS
    'Must equal the S3 Object Lock Retain Until Date. Never shorten this value.';
