import React, { useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { ArrowRight, Shield, Loader, Copy, Check } from 'lucide-react';
import { supabase } from '../../lib/supabase';

export default function MFAEnrollment({ onEnrollSuccess }) {
  const [step, setStep] = useState('start'); // 'start' | 'scan' | 'verify'
  const [enrollData, setEnrollData] = useState(null);
  const [verifyCode, setVerifyCode] = useState('');
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

const startEnrollment = async () => {
  setLoading(true);
  try {
    // 1. Check for existing unverified factors to prevent conflict
    const { data: factors } = await supabase.auth.mfa.listFactors();
    const staleFactors = factors?.all?.filter(f => f.status === 'unverified') || [];
    
    // 2. Clear them out
    for (const factor of staleFactors) {
      await supabase.auth.mfa.unenroll({ factorId: factor.id });
    }

    // 3. Now start a fresh enrollment
    const { data, error } = await supabase.auth.mfa.enroll({
      factorType: 'totp',
      issuer: 'SecureBase',
      friendlyName: 'Authy'
    });

    if (error) throw error;
    setEnrollData(data);
  } catch (err) {
    console.error("Enrollment error:", err.message);
  } finally {
    setLoading(false);
  }
};

  const handleVerify = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      const challenge = await supabase.auth.mfa.challenge({ factorId: enrollData.id });
      if (challenge.error) throw challenge.error;

      const { error: verifyError } = await supabase.auth.mfa.verify({
        factorId: enrollData.id,
        challengeId: challenge.data.id,
        code: verifyCode
      });

      if (verifyError) throw verifyError;
      onEnrollSuccess();
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(enrollData.totp.secret);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-md mx-auto bg-white p-8 rounded-2xl shadow-sm border border-slate-200 mt-12 text-center">
      <div className="bg-blue-600 w-12 h-12 rounded-xl flex items-center justify-center mx-auto mb-6 shadow-lg shadow-blue-200">
        <Shield className="text-white w-6 h-6" />
      </div>

      {step === 'start' && (
        <div className="space-y-6">
          <h2 className="text-2xl font-bold text-slate-900">Enable MFA</h2>
          <p className="text-slate-500 text-sm leading-relaxed">
            To access the SecureBase Compliance Vault, you must secure your account with a second factor. 
            We recommend using <strong>Authy</strong>.
          </p>
          <button 
            onClick={startEnrollment} 
            disabled={loading}
            className="w-full bg-blue-600 text-white py-3 rounded-xl font-bold hover:bg-blue-700 transition-all flex items-center justify-center gap-2"
          >
            {loading ? <Loader className="w-5 h-5 animate-spin" /> : "Start Setup"}
          </button>
        </div>
      )}

      {step === 'scan' && (
        <div className="flex flex-col items-center space-y-6">
          <h2 className="text-2xl font-bold text-slate-900">Scan QR Code</h2>
          <div className="p-4 bg-white rounded-2xl border shadow-sm inline-block">
            <QRCodeSVG 
              value={enrollData.totp.qr_code} 
              size={180}
              level="H"
              includeMargin={true}
            />
          </div>
          
          <div className="w-full bg-slate-50 p-4 rounded-xl border border-dashed border-slate-300 relative group">
            <p className="text-[10px] uppercase tracking-wider text-slate-400 font-bold mb-1 text-left">Manual Entry Key</p>
            <div className="flex items-center justify-between">
              <code className="text-xs break-all text-blue-600 font-mono text-left">{enrollData.totp.secret}</code>
              <button onClick={copyToClipboard} className="text-slate-400 hover:text-blue-600 transition-colors">
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>
          </div>

          <button 
            onClick={() => setStep('verify')} 
            className="w-full bg-slate-900 text-white py-3 rounded-xl font-bold hover:bg-slate-800 transition-all flex items-center justify-center gap-2"
          >
            I've Scanned It <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}

      {step === 'verify' && (
        <form onSubmit={handleVerify} className="space-y-6">
          <h2 className="text-2xl font-bold text-slate-900">Confirm Code</h2>
          <p className="text-sm text-slate-500">Enter the 6-digit code generated by your app.</p>
          <input
            type="text"
            maxLength="6"
            value={verifyCode}
            autoFocus
            onChange={(e) => setVerifyCode(e.target.value.replace(/\D/g, ''))}
            className="w-full text-center text-3xl tracking-[0.5em] font-mono py-3 border-2 border-slate-100 rounded-xl focus:border-blue-500 focus:outline-none"
            required
          />
          <button 
            type="submit" 
            disabled={loading || verifyCode.length !== 6}
            className="w-full bg-blue-600 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2"
          >
            {loading ? <Loader className="w-5 h-5 animate-spin" /> : "Verify and Enable"}
          </button>
        </form>
      )}

      {error && <p className="text-red-500 text-xs mt-6 font-semibold bg-red-50 p-3 rounded-lg border border-red-100">{error}</p>}
    </div>
  );
}
